scala_binary(
    name = "fill",
    srcs = ["DataFiller.scala"],
    main_class = "com.komanov.mysql.hashset.fill.DataFiller",
    deps = [
        "//src/com/komanov/mysql/hashset",
        "@mysql_hashset_maven//:mysql_mysql_connector_java",
    ],
)
