java_library(
    name = "base64",
    srcs = ["Base64Helper.java"],
    visibility = ["//src/com/komanov/jwt/base64:__subpackages__"],
    deps = [
        "@jwt//:commons_codec_commons_codec",
    ],
)

scala_library(
    name = "generator",
    srcs = ["PayloadGenerator.scala"],
    visibility = ["//src/com/komanov/jwt/base64:__subpackages__"],
)
