scala_specs2_junit(
    name = "tests",
    srcs = ["MacrosConcatTest.scala"],
    test_class = "src.com.komanov.stringformat.macros.tests.MacrosConcatTest",
    deps = [
        "//src/com/komanov/stringformat/macros",
    ],
)
