// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.komanov.serialization.domain.protos.events



@SerialVersionUID(0L)
final case class BlogComponentDataSetPb(
    id: com.google.protobuf.ByteString = com.google.protobuf.ByteString.EMPTY,
    name: String = "",
    rss: Boolean = false,
    tags: Boolean = false
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[BlogComponentDataSetPb] with com.trueaccord.lenses.Updatable[BlogComponentDataSetPb] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (id != com.google.protobuf.ByteString.EMPTY) { __size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, id) }
      if (name != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(2, name) }
      if (rss != false) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(3, rss) }
      if (tags != false) { __size += com.google.protobuf.CodedOutputStream.computeBoolSize(4, tags) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = id
        if (__v != com.google.protobuf.ByteString.EMPTY) {
          output.writeBytes(1, __v)
        }
      };
      {
        val __v = name
        if (__v != "") {
          output.writeString(2, __v)
        }
      };
      {
        val __v = rss
        if (__v != false) {
          output.writeBool(3, __v)
        }
      };
      {
        val __v = tags
        if (__v != false) {
          output.writeBool(4, __v)
        }
      };
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.komanov.serialization.domain.protos.events.BlogComponentDataSetPb = {
      var __id = this.id
      var __name = this.name
      var __rss = this.rss
      var __tags = this.tags
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __id = __input.readBytes()
          case 18 =>
            __name = __input.readString()
          case 24 =>
            __rss = __input.readBool()
          case 32 =>
            __tags = __input.readBool()
          case tag => __input.skipField(tag)
        }
      }
      com.komanov.serialization.domain.protos.events.BlogComponentDataSetPb(
          id = __id,
          name = __name,
          rss = __rss,
          tags = __tags
      )
    }
    def withId(__v: com.google.protobuf.ByteString): BlogComponentDataSetPb = copy(id = __v)
    def withName(__v: String): BlogComponentDataSetPb = copy(name = __v)
    def withRss(__v: Boolean): BlogComponentDataSetPb = copy(rss = __v)
    def withTags(__v: Boolean): BlogComponentDataSetPb = copy(tags = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = id
          if (__t != com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 2 => {
          val __t = name
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = rss
          if (__t != false) __t else null
        }
        case 4 => {
          val __t = tags
          if (__t != false) __t else null
        }
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.komanov.serialization.domain.protos.events.BlogComponentDataSetPb
}

object BlogComponentDataSetPb extends com.trueaccord.scalapb.GeneratedMessageCompanion[BlogComponentDataSetPb] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[BlogComponentDataSetPb] = this
  def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.komanov.serialization.domain.protos.events.BlogComponentDataSetPb = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.komanov.serialization.domain.protos.events.BlogComponentDataSetPb(
      __fieldsMap.getOrElse(__fields.get(0), com.google.protobuf.ByteString.EMPTY).asInstanceOf[com.google.protobuf.ByteString],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String],
      __fieldsMap.getOrElse(__fields.get(2), false).asInstanceOf[Boolean],
      __fieldsMap.getOrElse(__fields.get(3), false).asInstanceOf[Boolean]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = EventsProto.descriptor.getMessageTypes.get(24)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.komanov.serialization.domain.protos.events.BlogComponentDataSetPb(
  )
  implicit class BlogComponentDataSetPbLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, BlogComponentDataSetPb]) extends com.trueaccord.lenses.ObjectLens[UpperPB, BlogComponentDataSetPb](_l) {
    def id: com.trueaccord.lenses.Lens[UpperPB, com.google.protobuf.ByteString] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def name: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.name)((c_, f_) => c_.copy(name = f_))
    def rss: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.rss)((c_, f_) => c_.copy(rss = f_))
    def tags: com.trueaccord.lenses.Lens[UpperPB, Boolean] = field(_.tags)((c_, f_) => c_.copy(tags = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val NAME_FIELD_NUMBER = 2
  final val RSS_FIELD_NUMBER = 3
  final val TAGS_FIELD_NUMBER = 4
}
