// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.komanov.serialization.domain.protos.events



@SerialVersionUID(0L)
final case class PrimaryEntryPointSetPb(
    lookupKey: String = ""
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[PrimaryEntryPointSetPb] with com.trueaccord.lenses.Updatable[PrimaryEntryPointSetPb] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (lookupKey != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(1, lookupKey) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = lookupKey
        if (__v != "") {
          output.writeString(1, __v)
        }
      };
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.komanov.serialization.domain.protos.events.PrimaryEntryPointSetPb = {
      var __lookupKey = this.lookupKey
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __lookupKey = __input.readString()
          case tag => __input.skipField(tag)
        }
      }
      com.komanov.serialization.domain.protos.events.PrimaryEntryPointSetPb(
          lookupKey = __lookupKey
      )
    }
    def withLookupKey(__v: String): PrimaryEntryPointSetPb = copy(lookupKey = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = lookupKey
          if (__t != "") __t else null
        }
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.komanov.serialization.domain.protos.events.PrimaryEntryPointSetPb
}

object PrimaryEntryPointSetPb extends com.trueaccord.scalapb.GeneratedMessageCompanion[PrimaryEntryPointSetPb] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[PrimaryEntryPointSetPb] = this
  def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.komanov.serialization.domain.protos.events.PrimaryEntryPointSetPb = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.komanov.serialization.domain.protos.events.PrimaryEntryPointSetPb(
      __fieldsMap.getOrElse(__fields.get(0), "").asInstanceOf[String]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = EventsProto.descriptor.getMessageTypes.get(28)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.komanov.serialization.domain.protos.events.PrimaryEntryPointSetPb(
  )
  implicit class PrimaryEntryPointSetPbLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, PrimaryEntryPointSetPb]) extends com.trueaccord.lenses.ObjectLens[UpperPB, PrimaryEntryPointSetPb](_l) {
    def lookupKey: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.lookupKey)((c_, f_) => c_.copy(lookupKey = f_))
  }
  final val LOOKUPKEY_FIELD_NUMBER = 1
}
