// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.komanov.serialization.domain.protos.events



@SerialVersionUID(0L)
final case class TextComponentDataSetPb(
    id: com.google.protobuf.ByteString = com.google.protobuf.ByteString.EMPTY,
    text: String = ""
    ) extends com.trueaccord.scalapb.GeneratedMessage with com.trueaccord.scalapb.Message[TextComponentDataSetPb] with com.trueaccord.lenses.Updatable[TextComponentDataSetPb] {
    @transient
    private[this] var __serializedSizeCachedValue: Int = 0
    private[this] def __computeSerializedValue(): Int = {
      var __size = 0
      if (id != com.google.protobuf.ByteString.EMPTY) { __size += com.google.protobuf.CodedOutputStream.computeBytesSize(1, id) }
      if (text != "") { __size += com.google.protobuf.CodedOutputStream.computeStringSize(2, text) }
      __size
    }
    final override def serializedSize: Int = {
      var read = __serializedSizeCachedValue
      if (read == 0) {
        read = __computeSerializedValue()
        __serializedSizeCachedValue = read
      }
      read
    }
    def writeTo(output: com.google.protobuf.CodedOutputStream): Unit = {
      {
        val __v = id
        if (__v != com.google.protobuf.ByteString.EMPTY) {
          output.writeBytes(1, __v)
        }
      };
      {
        val __v = text
        if (__v != "") {
          output.writeString(2, __v)
        }
      };
    }
    def mergeFrom(__input: com.google.protobuf.CodedInputStream): com.komanov.serialization.domain.protos.events.TextComponentDataSetPb = {
      var __id = this.id
      var __text = this.text
      var _done__ = false
      while (!_done__) {
        val _tag__ = __input.readTag()
        _tag__ match {
          case 0 => _done__ = true
          case 10 =>
            __id = __input.readBytes()
          case 18 =>
            __text = __input.readString()
          case tag => __input.skipField(tag)
        }
      }
      com.komanov.serialization.domain.protos.events.TextComponentDataSetPb(
          id = __id,
          text = __text
      )
    }
    def withId(__v: com.google.protobuf.ByteString): TextComponentDataSetPb = copy(id = __v)
    def withText(__v: String): TextComponentDataSetPb = copy(text = __v)
    def getField(__field: com.google.protobuf.Descriptors.FieldDescriptor): scala.Any = {
      __field.getNumber match {
        case 1 => {
          val __t = id
          if (__t != com.google.protobuf.ByteString.EMPTY) __t else null
        }
        case 2 => {
          val __t = text
          if (__t != "") __t else null
        }
      }
    }
    override def toString: String = com.trueaccord.scalapb.TextFormat.printToUnicodeString(this)
    def companion = com.komanov.serialization.domain.protos.events.TextComponentDataSetPb
}

object TextComponentDataSetPb extends com.trueaccord.scalapb.GeneratedMessageCompanion[TextComponentDataSetPb] {
  implicit def messageCompanion: com.trueaccord.scalapb.GeneratedMessageCompanion[TextComponentDataSetPb] = this
  def fromFieldsMap(__fieldsMap: Map[com.google.protobuf.Descriptors.FieldDescriptor, scala.Any]): com.komanov.serialization.domain.protos.events.TextComponentDataSetPb = {
    require(__fieldsMap.keys.forall(_.getContainingType() == descriptor), "FieldDescriptor does not match message type.")
    val __fields = descriptor.getFields
    com.komanov.serialization.domain.protos.events.TextComponentDataSetPb(
      __fieldsMap.getOrElse(__fields.get(0), com.google.protobuf.ByteString.EMPTY).asInstanceOf[com.google.protobuf.ByteString],
      __fieldsMap.getOrElse(__fields.get(1), "").asInstanceOf[String]
    )
  }
  def descriptor: com.google.protobuf.Descriptors.Descriptor = EventsProto.descriptor.getMessageTypes.get(22)
  def messageCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__field)
  def enumCompanionForField(__field: com.google.protobuf.Descriptors.FieldDescriptor): com.trueaccord.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__field)
  lazy val defaultInstance = com.komanov.serialization.domain.protos.events.TextComponentDataSetPb(
  )
  implicit class TextComponentDataSetPbLens[UpperPB](_l: com.trueaccord.lenses.Lens[UpperPB, TextComponentDataSetPb]) extends com.trueaccord.lenses.ObjectLens[UpperPB, TextComponentDataSetPb](_l) {
    def id: com.trueaccord.lenses.Lens[UpperPB, com.google.protobuf.ByteString] = field(_.id)((c_, f_) => c_.copy(id = f_))
    def text: com.trueaccord.lenses.Lens[UpperPB, String] = field(_.text)((c_, f_) => c_.copy(text = f_))
  }
  final val ID_FIELD_NUMBER = 1
  final val TEXT_FIELD_NUMBER = 2
}
