language: java

jdk:
  - openjdk8

dist: trusty

os:
  - linux

before_install:
  - echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y bazel

script:
  - sudo bazel test -k --test_output=errors --test_tmpdir=/tmp --curses=no //...

notifications:
  email: false
