language: java

jdk:
  - openjdk17

dist: focal

os:
  - linux

before_install:
  - sudo apt install apt-transport-https curl gnupg
  - curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg
  - sudo mv bazel-archive-keyring.gpg /usr/share/keyrings
  - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - sudo apt-get -qq update
  - sudo apt-get install -y bazel

script:
  - sudo bazel test -k --test_output=errors --test_tmpdir=/tmp --curses=no //...

notifications:
  email: false
