dist: trusty
language: java

os:
  - linux

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt testing jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y bazel

script:
  - TARGET="//..."
  - BAZEL_OPTS="--output_base=$HOME/.cache/bazel"
  - echo 'fetching dependencies...' && echo -en 'travis_fold:start:fetch\\r'
  - bazel $BAZEL_OPTS fetch $TARGET
  - echo -en 'travis_fold:end:fetch\\r'
  - echo 'building...' && echo -en 'travis_fold:start:build\\r'
  - bazel $BAZEL_OPTS build $TARGET
  - echo -en 'travis_fold:end:build\\r'
  - echo 'running tests...' && echo -en 'travis_fold:start:test\\r'
  - bazel $BAZEL_OPTS test $TARGET
  - echo -en 'travis_fold:end:test\\r'

notifications:
  email: false
