dist: trusty
language: java

os:
  - linux

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt testing jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y bazel

script:
  - TARGET="//..."
  - BAZEL_OPTS="--output_base=$HOME/.cache/bazel --batch --host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m --noshow_loading_progress"
  - BAZEL_BUILD_OPTS="--verbose_failures --worker_verbose --local_resources=400,2,1.0 --strategy=Javac=worker --spawn_strategy=standalone --genrule_strategy=standalone"
  - BAZEL_TEST_OPTS="--test_output=errors --test_strategy=standalone"
  - echo 'fetching dependencies...' && echo -en 'travis_fold:start:fetch\\r'
  - bazel $BAZEL_OPTS fetch $TARGET $FLAGS
  - echo -en 'travis_fold:end:fetch\\r'
  - echo 'building...' && echo -en 'travis_fold:start:build\\r'
  - bazel $BAZEL_OPTS build $BAZEL_BUILD_OPTS $TARGET $FLAGS
  - echo -en 'travis_fold:end:build\\r'
  - echo 'running tests...' && echo -en 'travis_fold:start:test\\r'
  - bazel $BAZEL_OPTS test $BAZEL_BUILD_OPTS $BAZEL_TEST_OPTS $TARGET $FLAGS
  - echo -en 'travis_fold:end:test\\r'

notifications:
  email: false
