dist: trusty
sudo: required
language: java

os:
  - linux

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt testing jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install bazel

script:
  - |
    bazel \
      --output_base=$HOME/.cache/bazel \
      --batch \
      --host_jvm_args=-Xmx500m \
      --host_jvm_args=-Xms500m \
      test \
      --verbose_failures \
      --test_output=errors \
      --test_strategy=standalone \
      --spawn_strategy=standalone \
      --genrule_strategy=standalone \
      --local_resources=400,2,1.0 \
      --worker_verbose \
      --strategy=Javac=worker \
      //... \
      $FLAGS

notifications:
  email: false
