language: java

jdk:
  - openjdk8

dist: trusty

os:
  - linux

before_install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt testing jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  - sudo apt-get -qq update
  - sudo apt-get install -y bazel

script:
  - sudo bazel --action_env=TEST_TMPDIR=$HOME/bazel_exec test -k --test_output=errors --curses=no //...

notifications:
  email: false
