scala_library(
    name = "api",
    srcs = glob(["*.scala"]),
    visibility = ["//src/com/komanov/serialization:__subpackages__"],
    exports = [
        "//src/com/komanov/serialization/domain",
    ],
    deps = [
        "//src/com/komanov/serialization/domain",
    ],
)
