scala_library(
    name = "alloc",
    srcs = ["Allocator.scala"],
    visibility = [
        "//src/com/komanov/nativeaccess:__subpackages__",
        "//src/com/komanov/offheap:__subpackages__",
    ],
)
