scala_benchmark_jmh(
    name = "jmh",
    srcs = ["MysqlBlobBenchmarks.scala"],
    deps = [
        "//src/com/komanov/compression",
        "//src/com/komanov/mysql/blob",
        "@mysql_blob_maven//:mysql_mysql_connector_java",
    ],
)
