scala_specs2_junit(
    name = "tests",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/com/komanov/io",
        "@maven//:org_mockito_mockito_core",
        "@maven//:org_specs2_specs2_mock_2_13",
    ],
)
