scala_library(
    name = "jmh",
    srcs = glob(["*.scala"]),
    visibility = ["//visibility:public"],
    exports = [
        "@io_bazel_rules_scala_org_openjdk_jmh_jmh_core",
    ],
    deps = [
        "@io_bazel_rules_scala_org_openjdk_jmh_jmh_core",
    ],
)
