scala_library(
    name = "jmh",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/com/komanov/mysql/streaming",
        "//third_party:com_wix_wix_embedded_mysql",
        "//third_party:org_openjdk_jmh_jmh_core",
    ],
)
