java_binary(
    name = "perf",
    srcs = ["PerfTester.java"],
    main_class = "com.komanov.redis.perf.PerfTester",
    deps = [
        "//src/com/komanov/redis",
        "@offheap_maven//:io_lettuce_lettuce_core",
    ],
)
