package(default_visibility = ["//src/com/komanov/ver:__subpackages__"])

scala_library(
    name = "ver",
    srcs = [
        "ParseVersionNoAllocUtil.java",
        "ParseVersionUtil.java",
        "Version.scala",
        "VersionNoAlloc.scala",
    ],
)
