scala_binary(
    name = "tmp",
    srcs = glob(["*.scala"]),
    main_class = "com.komanov.serialization.tmp.ConvertApp",
    deps = [
        "//third_party:com_fasterxml_jackson_core_jackson_core",
        "//third_party:com_fasterxml_jackson_core_jackson_databind",
        "//third_party:com_fasterxml_jackson_module_jackson_module_scala_2_11",
    ],
)
