/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.komanov.serialization.domain.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-08-14")
public class FreeEntryPointPb implements org.apache.thrift.TBase<FreeEntryPointPb, FreeEntryPointPb._Fields>, java.io.Serializable, Cloneable, Comparable<FreeEntryPointPb> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("FreeEntryPointPb");

  private static final org.apache.thrift.protocol.TField USER_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("userName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SITE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("siteName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField PRIMARY_FIELD_DESC = new org.apache.thrift.protocol.TField("primary", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new FreeEntryPointPbStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new FreeEntryPointPbTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String userName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String siteName; // optional
  public boolean primary; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    USER_NAME((short)1, "userName"),
    SITE_NAME((short)2, "siteName"),
    PRIMARY((short)3, "primary");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // USER_NAME
          return USER_NAME;
        case 2: // SITE_NAME
          return SITE_NAME;
        case 3: // PRIMARY
          return PRIMARY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PRIMARY_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.USER_NAME,_Fields.SITE_NAME,_Fields.PRIMARY};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.USER_NAME, new org.apache.thrift.meta_data.FieldMetaData("userName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SITE_NAME, new org.apache.thrift.meta_data.FieldMetaData("siteName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PRIMARY, new org.apache.thrift.meta_data.FieldMetaData("primary", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(FreeEntryPointPb.class, metaDataMap);
  }

  public FreeEntryPointPb() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public FreeEntryPointPb(FreeEntryPointPb other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetUserName()) {
      this.userName = other.userName;
    }
    if (other.isSetSiteName()) {
      this.siteName = other.siteName;
    }
    this.primary = other.primary;
  }

  public FreeEntryPointPb deepCopy() {
    return new FreeEntryPointPb(this);
  }

  @Override
  public void clear() {
    this.userName = null;
    this.siteName = null;
    setPrimaryIsSet(false);
    this.primary = false;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getUserName() {
    return this.userName;
  }

  public FreeEntryPointPb setUserName(@org.apache.thrift.annotation.Nullable java.lang.String userName) {
    this.userName = userName;
    return this;
  }

  public void unsetUserName() {
    this.userName = null;
  }

  /** Returns true if field userName is set (has been assigned a value) and false otherwise */
  public boolean isSetUserName() {
    return this.userName != null;
  }

  public void setUserNameIsSet(boolean value) {
    if (!value) {
      this.userName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSiteName() {
    return this.siteName;
  }

  public FreeEntryPointPb setSiteName(@org.apache.thrift.annotation.Nullable java.lang.String siteName) {
    this.siteName = siteName;
    return this;
  }

  public void unsetSiteName() {
    this.siteName = null;
  }

  /** Returns true if field siteName is set (has been assigned a value) and false otherwise */
  public boolean isSetSiteName() {
    return this.siteName != null;
  }

  public void setSiteNameIsSet(boolean value) {
    if (!value) {
      this.siteName = null;
    }
  }

  public boolean isPrimary() {
    return this.primary;
  }

  public FreeEntryPointPb setPrimary(boolean primary) {
    this.primary = primary;
    setPrimaryIsSet(true);
    return this;
  }

  public void unsetPrimary() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PRIMARY_ISSET_ID);
  }

  /** Returns true if field primary is set (has been assigned a value) and false otherwise */
  public boolean isSetPrimary() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PRIMARY_ISSET_ID);
  }

  public void setPrimaryIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PRIMARY_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case USER_NAME:
      if (value == null) {
        unsetUserName();
      } else {
        setUserName((java.lang.String)value);
      }
      break;

    case SITE_NAME:
      if (value == null) {
        unsetSiteName();
      } else {
        setSiteName((java.lang.String)value);
      }
      break;

    case PRIMARY:
      if (value == null) {
        unsetPrimary();
      } else {
        setPrimary((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case USER_NAME:
      return getUserName();

    case SITE_NAME:
      return getSiteName();

    case PRIMARY:
      return isPrimary();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case USER_NAME:
      return isSetUserName();
    case SITE_NAME:
      return isSetSiteName();
    case PRIMARY:
      return isSetPrimary();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof FreeEntryPointPb)
      return this.equals((FreeEntryPointPb)that);
    return false;
  }

  public boolean equals(FreeEntryPointPb that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_userName = true && this.isSetUserName();
    boolean that_present_userName = true && that.isSetUserName();
    if (this_present_userName || that_present_userName) {
      if (!(this_present_userName && that_present_userName))
        return false;
      if (!this.userName.equals(that.userName))
        return false;
    }

    boolean this_present_siteName = true && this.isSetSiteName();
    boolean that_present_siteName = true && that.isSetSiteName();
    if (this_present_siteName || that_present_siteName) {
      if (!(this_present_siteName && that_present_siteName))
        return false;
      if (!this.siteName.equals(that.siteName))
        return false;
    }

    boolean this_present_primary = true && this.isSetPrimary();
    boolean that_present_primary = true && that.isSetPrimary();
    if (this_present_primary || that_present_primary) {
      if (!(this_present_primary && that_present_primary))
        return false;
      if (this.primary != that.primary)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetUserName()) ? 131071 : 524287);
    if (isSetUserName())
      hashCode = hashCode * 8191 + userName.hashCode();

    hashCode = hashCode * 8191 + ((isSetSiteName()) ? 131071 : 524287);
    if (isSetSiteName())
      hashCode = hashCode * 8191 + siteName.hashCode();

    hashCode = hashCode * 8191 + ((isSetPrimary()) ? 131071 : 524287);
    if (isSetPrimary())
      hashCode = hashCode * 8191 + ((primary) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(FreeEntryPointPb other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetUserName(), other.isSetUserName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userName, other.userName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSiteName(), other.isSetSiteName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSiteName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.siteName, other.siteName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPrimary(), other.isSetPrimary());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPrimary()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.primary, other.primary);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("FreeEntryPointPb(");
    boolean first = true;

    if (isSetUserName()) {
      sb.append("userName:");
      if (this.userName == null) {
        sb.append("null");
      } else {
        sb.append(this.userName);
      }
      first = false;
    }
    if (isSetSiteName()) {
      if (!first) sb.append(", ");
      sb.append("siteName:");
      if (this.siteName == null) {
        sb.append("null");
      } else {
        sb.append(this.siteName);
      }
      first = false;
    }
    if (isSetPrimary()) {
      if (!first) sb.append(", ");
      sb.append("primary:");
      sb.append(this.primary);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class FreeEntryPointPbStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public FreeEntryPointPbStandardScheme getScheme() {
      return new FreeEntryPointPbStandardScheme();
    }
  }

  private static class FreeEntryPointPbStandardScheme extends org.apache.thrift.scheme.StandardScheme<FreeEntryPointPb> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, FreeEntryPointPb struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // USER_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.userName = iprot.readString();
              struct.setUserNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SITE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.siteName = iprot.readString();
              struct.setSiteNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PRIMARY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.primary = iprot.readBool();
              struct.setPrimaryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, FreeEntryPointPb struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.userName != null) {
        if (struct.isSetUserName()) {
          oprot.writeFieldBegin(USER_NAME_FIELD_DESC);
          oprot.writeString(struct.userName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.siteName != null) {
        if (struct.isSetSiteName()) {
          oprot.writeFieldBegin(SITE_NAME_FIELD_DESC);
          oprot.writeString(struct.siteName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetPrimary()) {
        oprot.writeFieldBegin(PRIMARY_FIELD_DESC);
        oprot.writeBool(struct.primary);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class FreeEntryPointPbTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public FreeEntryPointPbTupleScheme getScheme() {
      return new FreeEntryPointPbTupleScheme();
    }
  }

  private static class FreeEntryPointPbTupleScheme extends org.apache.thrift.scheme.TupleScheme<FreeEntryPointPb> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, FreeEntryPointPb struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetUserName()) {
        optionals.set(0);
      }
      if (struct.isSetSiteName()) {
        optionals.set(1);
      }
      if (struct.isSetPrimary()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetUserName()) {
        oprot.writeString(struct.userName);
      }
      if (struct.isSetSiteName()) {
        oprot.writeString(struct.siteName);
      }
      if (struct.isSetPrimary()) {
        oprot.writeBool(struct.primary);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, FreeEntryPointPb struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.userName = iprot.readString();
        struct.setUserNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.siteName = iprot.readString();
        struct.setSiteNameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.primary = iprot.readBool();
        struct.setPrimaryIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

