/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.komanov.serialization.domain.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-08-14")
public class SiteFlagRemovedPb implements org.apache.thrift.TBase<SiteFlagRemovedPb, SiteFlagRemovedPb._Fields>, java.io.Serializable, Cloneable, Comparable<SiteFlagRemovedPb> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("SiteFlagRemovedPb");

  private static final org.apache.thrift.protocol.TField SITE_FLAG_FIELD_DESC = new org.apache.thrift.protocol.TField("siteFlag", org.apache.thrift.protocol.TType.I32, (short)1);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new SiteFlagRemovedPbStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new SiteFlagRemovedPbTupleSchemeFactory();

  /**
   * 
   * @see SiteFlagPb
   */
  public @org.apache.thrift.annotation.Nullable SiteFlagPb siteFlag; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see SiteFlagPb
     */
    SITE_FLAG((short)1, "siteFlag");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SITE_FLAG
          return SITE_FLAG;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final _Fields optionals[] = {_Fields.SITE_FLAG};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SITE_FLAG, new org.apache.thrift.meta_data.FieldMetaData("siteFlag", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, SiteFlagPb.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(SiteFlagRemovedPb.class, metaDataMap);
  }

  public SiteFlagRemovedPb() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public SiteFlagRemovedPb(SiteFlagRemovedPb other) {
    if (other.isSetSiteFlag()) {
      this.siteFlag = other.siteFlag;
    }
  }

  public SiteFlagRemovedPb deepCopy() {
    return new SiteFlagRemovedPb(this);
  }

  @Override
  public void clear() {
    this.siteFlag = null;
  }

  /**
   * 
   * @see SiteFlagPb
   */
  @org.apache.thrift.annotation.Nullable
  public SiteFlagPb getSiteFlag() {
    return this.siteFlag;
  }

  /**
   * 
   * @see SiteFlagPb
   */
  public SiteFlagRemovedPb setSiteFlag(@org.apache.thrift.annotation.Nullable SiteFlagPb siteFlag) {
    this.siteFlag = siteFlag;
    return this;
  }

  public void unsetSiteFlag() {
    this.siteFlag = null;
  }

  /** Returns true if field siteFlag is set (has been assigned a value) and false otherwise */
  public boolean isSetSiteFlag() {
    return this.siteFlag != null;
  }

  public void setSiteFlagIsSet(boolean value) {
    if (!value) {
      this.siteFlag = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SITE_FLAG:
      if (value == null) {
        unsetSiteFlag();
      } else {
        setSiteFlag((SiteFlagPb)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SITE_FLAG:
      return getSiteFlag();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SITE_FLAG:
      return isSetSiteFlag();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof SiteFlagRemovedPb)
      return this.equals((SiteFlagRemovedPb)that);
    return false;
  }

  public boolean equals(SiteFlagRemovedPb that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_siteFlag = true && this.isSetSiteFlag();
    boolean that_present_siteFlag = true && that.isSetSiteFlag();
    if (this_present_siteFlag || that_present_siteFlag) {
      if (!(this_present_siteFlag && that_present_siteFlag))
        return false;
      if (!this.siteFlag.equals(that.siteFlag))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSiteFlag()) ? 131071 : 524287);
    if (isSetSiteFlag())
      hashCode = hashCode * 8191 + siteFlag.getValue();

    return hashCode;
  }

  @Override
  public int compareTo(SiteFlagRemovedPb other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSiteFlag(), other.isSetSiteFlag());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSiteFlag()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.siteFlag, other.siteFlag);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("SiteFlagRemovedPb(");
    boolean first = true;

    if (isSetSiteFlag()) {
      sb.append("siteFlag:");
      if (this.siteFlag == null) {
        sb.append("null");
      } else {
        sb.append(this.siteFlag);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class SiteFlagRemovedPbStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SiteFlagRemovedPbStandardScheme getScheme() {
      return new SiteFlagRemovedPbStandardScheme();
    }
  }

  private static class SiteFlagRemovedPbStandardScheme extends org.apache.thrift.scheme.StandardScheme<SiteFlagRemovedPb> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, SiteFlagRemovedPb struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SITE_FLAG
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.siteFlag = com.komanov.serialization.domain.thrift.SiteFlagPb.findByValue(iprot.readI32());
              struct.setSiteFlagIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, SiteFlagRemovedPb struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.siteFlag != null) {
        if (struct.isSetSiteFlag()) {
          oprot.writeFieldBegin(SITE_FLAG_FIELD_DESC);
          oprot.writeI32(struct.siteFlag.getValue());
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class SiteFlagRemovedPbTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public SiteFlagRemovedPbTupleScheme getScheme() {
      return new SiteFlagRemovedPbTupleScheme();
    }
  }

  private static class SiteFlagRemovedPbTupleScheme extends org.apache.thrift.scheme.TupleScheme<SiteFlagRemovedPb> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, SiteFlagRemovedPb struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSiteFlag()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetSiteFlag()) {
        oprot.writeI32(struct.siteFlag.getValue());
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, SiteFlagRemovedPb struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.siteFlag = com.komanov.serialization.domain.thrift.SiteFlagPb.findByValue(iprot.readI32());
        struct.setSiteFlagIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

