scala_library(
    name = "readlines",
    srcs = glob([
        "*.scala",
        "*.java",
    ]),
    visibility = [
        "//src/com/komanov/readlines/bin:__pkg__",
        "//src/com/komanov/readlines/jmh:__pkg__",
        "//src/com/komanov/readlines/tests:__pkg__",
    ],
)
