scala_specs2_junit(
    name = "tests",
    srcs = glob(["*.scala"]),
    test_class = "com.komanov.serialization.domain.tests.EventProcessorTest",
    deps = [
        "//src/com/komanov/serialization/domain",
        "//src/com/komanov/serialization/domain/testdata",
    ],
)
