scala_specs2_junit(
    name = "tests",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/com/komanov/serialization/domain",
        "//src/com/komanov/serialization/domain/testdata",
    ],
)
