#scala_specs2_junit(
#    name = "tests",
#    size = "medium",
#    srcs = glob(["*.scala"]),
#    runtime_deps = [
#        "@mysql_streaming_maven//:mysql_mysql_connector_java",
#        "@mysql_streaming_maven//:org_drizzle_jdbc_drizzle_jdbc",
#        "@mysql_streaming_maven//:org_mariadb_jdbc_mariadb_java_client",
#    ],
#    deps = [
#        "//src/com/komanov/mysql/streaming",
#        "@mysql_streaming_maven//:com_wix_wix_embedded_mysql",
#    ],
#)
