java_library(
    name = "uuidhashmap",
    srcs = ["UuidToIntHashMap.java"],
    visibility = [
        "//src/com/komanov/offheap:__subpackages__",
    ],
    deps = [
        "//src/com/komanov/offheap/alloc",
    ],
)
