scala_benchmark_jmh(
    name = "jmh",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/com/komanov/jwt/base64",
        "//src/com/komanov/jwt/base64/jmh:jmh_base",
        "//src/com/komanov/jwt/base64/jni",
    ],
)
