package(default_visibility = ["//src/com/komanov/serialization:__subpackages__"])

java_library(
    name = "capnproto",
    srcs = glob(["*.java"]),
    deps = [
        "@scala_serialization_maven//:org_capnproto_runtime",
    ],
)
