scala_specs2_junit(
    name = "tests",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/com/komanov/stringformat/macros",
        "//third_party:org_mockito_mockito_core",
        "//third_party:org_specs2_specs2_mock_2_11",
    ],
)
