scala_library(
    name = "pool",
    srcs = glob(["*.scala", "*.java"]),
    visibility = [
        "//src/com/komanov/mysql/pool:__subpackages__",
    ],
    deps = [
        "@mysql_streaming_maven//:mysql_mysql_connector_java",
    ],
)
