scala_library(
    name = "jmh",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/com/komanov/stringformat",
        "//src/com/komanov/stringformat/macros",
        "//third_party:org_openjdk_jmh_jmh_core",
    ],
)
