scala_specs2_junit(
    name = "mockito-and-mutable",
    srcs = ["MockitoAndMutableTest.scala"],
    test_class = "com.komanov.junk.mockito.MockitoAndMutableTest",
)

scala_specs2_junit(
    name = "respond-extension",
    srcs = ["RespondExtensionTest.scala"],
    test_class = "com.komanov.junk.mockito.RespondExtensionTest",
)
