scala_specs2_junit(
    name = "tests",
    srcs = glob(["*.scala"]),
    runtime_deps = [
        "@maven//:org_slf4j_slf4j_api",
    ],
    deps = [
        "//src/com/komanov/stringformat",
    ],
)
