/**
 * Generated by Scrooge
 *   version: 4.7.0
 *   rev: d9d56174937f524a1981b38ebd6280eef7eeda4a
 *   built at: 20160427-121531
 */
package com.komanov.serialization.domain.thriftscala

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object PageComponentDataPb extends ThriftStructCodec3[PageComponentDataPb] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("PageComponentDataPb")
  val TextField = new TField("text", TType.STRUCT, 1)
  val TextFieldManifest = implicitly[Manifest[com.komanov.serialization.domain.thriftscala.TextComponentDataPb]]
  val ButtonField = new TField("button", TType.STRUCT, 2)
  val ButtonFieldManifest = implicitly[Manifest[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb]]
  val BlogField = new TField("blog", TType.STRUCT, 3)
  val BlogFieldManifest = implicitly[Manifest[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      TextField,
      true,
      false,
      TextFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      ButtonField,
      true,
      false,
      ButtonFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    ),
    new ThriftStructFieldInfo(
      BlogField,
      true,
      false,
      BlogFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: PageComponentDataPb): Unit = {
  }

  def withoutPassthroughFields(original: PageComponentDataPb): PageComponentDataPb =
    new Immutable(
      text =
        {
          val field = original.text
          field.map { field =>
            com.komanov.serialization.domain.thriftscala.TextComponentDataPb.withoutPassthroughFields(field)
          }
        },
      button =
        {
          val field = original.button
          field.map { field =>
            com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb.withoutPassthroughFields(field)
          }
        },
      blog =
        {
          val field = original.blog
          field.map { field =>
            com.komanov.serialization.domain.thriftscala.BlogComponentDataPb.withoutPassthroughFields(field)
          }
        }
    )

  override def encode(_item: PageComponentDataPb, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): PageComponentDataPb = {

    var text: Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = None
    var button: Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = None
    var blog: Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = None

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRUCT =>
    
                text = Some(readTextValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'text' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRUCT =>
    
                button = Some(readButtonValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'button' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRUCT =>
    
                blog = Some(readBlogValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'blog' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      text,
      button,
      blog,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): PageComponentDataPb =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): PageComponentDataPb = {
    var text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = _root_.scala.None
    var button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = _root_.scala.None
    var blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.STRUCT =>
                text = _root_.scala.Some(readTextValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'text' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 2 =>
            _field.`type` match {
              case TType.STRUCT =>
                button = _root_.scala.Some(readButtonValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'button' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case 3 =>
            _field.`type` match {
              case TType.STRUCT =>
                blog = _root_.scala.Some(readBlogValue(_iprot))
              case _actualType =>
                val _expectedType = TType.STRUCT
                throw new TProtocolException(
                  "Received wrong type for field 'blog' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      text,
      button,
      blog,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = _root_.scala.None,
    button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = _root_.scala.None,
    blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = _root_.scala.None
  ): PageComponentDataPb =
    new Immutable(
      text,
      button,
      blog
    )

  def unapply(_item: PageComponentDataPb): _root_.scala.Option[scala.Product3[Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb], Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb], Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb]]] = _root_.scala.Some(_item)


  @inline private def readTextValue(_iprot: TProtocol): com.komanov.serialization.domain.thriftscala.TextComponentDataPb = {
    com.komanov.serialization.domain.thriftscala.TextComponentDataPb.decode(_iprot)
  }

  @inline private def writeTextField(text_item: com.komanov.serialization.domain.thriftscala.TextComponentDataPb, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(TextField)
    writeTextValue(text_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeTextValue(text_item: com.komanov.serialization.domain.thriftscala.TextComponentDataPb, _oprot: TProtocol): Unit = {
    text_item.write(_oprot)
  }

  @inline private def readButtonValue(_iprot: TProtocol): com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb = {
    com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb.decode(_iprot)
  }

  @inline private def writeButtonField(button_item: com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(ButtonField)
    writeButtonValue(button_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeButtonValue(button_item: com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb, _oprot: TProtocol): Unit = {
    button_item.write(_oprot)
  }

  @inline private def readBlogValue(_iprot: TProtocol): com.komanov.serialization.domain.thriftscala.BlogComponentDataPb = {
    com.komanov.serialization.domain.thriftscala.BlogComponentDataPb.decode(_iprot)
  }

  @inline private def writeBlogField(blog_item: com.komanov.serialization.domain.thriftscala.BlogComponentDataPb, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(BlogField)
    writeBlogValue(blog_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeBlogValue(blog_item: com.komanov.serialization.domain.thriftscala.BlogComponentDataPb, _oprot: TProtocol): Unit = {
    blog_item.write(_oprot)
  }


  object Immutable extends ThriftStructCodec3[PageComponentDataPb] {
    override def encode(_item: PageComponentDataPb, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): PageComponentDataPb = PageComponentDataPb.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[PageComponentDataPb] = PageComponentDataPb.metaData
  }

  /**
   * The default read-only implementation of PageComponentDataPb.  You typically should not need to
   * directly reference this class; instead, use the PageComponentDataPb.apply method to construct
   * new instances.
   */
  class Immutable(
      val text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb],
      val button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb],
      val blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PageComponentDataPb {
    def this(
      text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = _root_.scala.None,
      button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = _root_.scala.None,
      blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = _root_.scala.None
    ) = this(
      text,
      button,
      blog,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb],
      val button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb],
      val blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends PageComponentDataPb {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the PageComponentDataPb trait with additional state or
   * behavior and implement the read-only methods from PageComponentDataPb using an underlying
   * instance.
   */
  trait Proxy extends PageComponentDataPb {
    protected def _underlying_PageComponentDataPb: PageComponentDataPb
    override def text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = _underlying_PageComponentDataPb.text
    override def button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = _underlying_PageComponentDataPb.button
    override def blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = _underlying_PageComponentDataPb.blog
    override def _passthroughFields = _underlying_PageComponentDataPb._passthroughFields
  }
}

trait PageComponentDataPb
  extends ThriftStruct
  with scala.Product3[Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb], Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb], Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb]]
  with java.io.Serializable
{
  import PageComponentDataPb._

  def text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb]
  def button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb]
  def blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = text
  def _2 = button
  def _3 = blog


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (text.isDefined) {
                writeTextValue(text.get, _oprot)
                _root_.scala.Some(PageComponentDataPb.TextField)
              } else {
                _root_.scala.None
              }
            case 2 =>
              if (button.isDefined) {
                writeButtonValue(button.get, _oprot)
                _root_.scala.Some(PageComponentDataPb.ButtonField)
              } else {
                _root_.scala.None
              }
            case 3 =>
              if (blog.isDefined) {
                writeBlogValue(blog.get, _oprot)
                _root_.scala.Some(PageComponentDataPb.BlogField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): PageComponentDataPb = {
    var text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = this.text
    var button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = this.button
    var blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = this.blog
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        text = _root_.scala.Some(readTextValue(_blob.read))
      case 2 =>
        button = _root_.scala.Some(readButtonValue(_blob.read))
      case 3 =>
        blog = _root_.scala.Some(readBlogValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      text,
      button,
      blog,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): PageComponentDataPb = {
    var text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = this.text
    var button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = this.button
    var blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = this.blog

    _fieldId match {
      case 1 =>
        text = _root_.scala.None
      case 2 =>
        button = _root_.scala.None
      case 3 =>
        blog = _root_.scala.None
      case _ =>
    }
    new Immutable(
      text,
      button,
      blog,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetText: PageComponentDataPb = unsetField(1)

  def unsetButton: PageComponentDataPb = unsetField(2)

  def unsetBlog: PageComponentDataPb = unsetField(3)


  override def write(_oprot: TProtocol): Unit = {
    PageComponentDataPb.validate(this)
    _oprot.writeStructBegin(Struct)
    if (text.isDefined) writeTextField(text.get, _oprot)
    if (button.isDefined) writeButtonField(button.get, _oprot)
    if (blog.isDefined) writeBlogField(blog.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    text: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.TextComponentDataPb] = this.text,
    button: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.ButtonComponentDataPb] = this.button,
    blog: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.BlogComponentDataPb] = this.blog,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): PageComponentDataPb =
    new Immutable(
      text,
      button,
      blog,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[PageComponentDataPb]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[PageComponentDataPb]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 3

  override def productElement(n: Int): Any = n match {
    case 0 => this.text
    case 1 => this.button
    case 2 => this.blog
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "PageComponentDataPb"
}