/**
 * Generated by Scrooge
 *   version: 4.7.0
 *   rev: d9d56174937f524a1981b38ebd6280eef7eeda4a
 *   built at: 20160427-121531
 */
package com.komanov.serialization.domain.thriftscala

import com.twitter.scrooge.{
  LazyTProtocol,
  TFieldBlob, ThriftException, ThriftStruct, ThriftStructCodec3, ThriftStructFieldInfo,
  ThriftStructMetaData, ThriftUtil}
import org.apache.thrift.protocol._
import org.apache.thrift.transport.{TMemoryBuffer, TTransport}
import java.nio.ByteBuffer
import java.util.Arrays
import scala.collection.immutable.{Map => immutable$Map}
import scala.collection.mutable.Builder
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, Buffer => mutable$Buffer,
  HashMap => mutable$HashMap, HashSet => mutable$HashSet}
import scala.collection.{Map, Set}


object SiteFlagAddedPb extends ThriftStructCodec3[SiteFlagAddedPb] {
  private val NoPassthroughFields = immutable$Map.empty[Short, TFieldBlob]
  val Struct = new TStruct("SiteFlagAddedPb")
  val SiteFlagField = new TField("siteFlag", TType.ENUM, 1)
  val SiteFlagFieldI32 = new TField("siteFlag", TType.I32, 1)
  val SiteFlagFieldManifest = implicitly[Manifest[com.komanov.serialization.domain.thriftscala.SiteFlagPb]]

  /**
   * Field information in declaration order.
   */
  lazy val fieldInfos: scala.List[ThriftStructFieldInfo] = scala.List[ThriftStructFieldInfo](
    new ThriftStructFieldInfo(
      SiteFlagField,
      true,
      false,
      SiteFlagFieldManifest,
      _root_.scala.None,
      _root_.scala.None,
      immutable$Map.empty[String, String],
      immutable$Map.empty[String, String]
    )
  )

  lazy val structAnnotations: immutable$Map[String, String] =
    immutable$Map.empty[String, String]

  /**
   * Checks that all required fields are non-null.
   */
  def validate(_item: SiteFlagAddedPb): Unit = {
  }

  def withoutPassthroughFields(original: SiteFlagAddedPb): SiteFlagAddedPb =
    new Immutable(
      siteFlag =
        {
          val field = original.siteFlag
          field.map { field =>
            field
          }
        }
    )

  override def encode(_item: SiteFlagAddedPb, _oproto: TProtocol): Unit = {
    _item.write(_oproto)
  }

  private[this] def lazyDecode(_iprot: LazyTProtocol): SiteFlagAddedPb = {

    var siteFlag: Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = None

    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false
    val _start_offset = _iprot.offset

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
    
                siteFlag = Some(readSiteFlagValue(_iprot))
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'siteFlag' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new LazyImmutable(
      _iprot,
      _iprot.buffer,
      _start_offset,
      _iprot.offset,
      siteFlag,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  override def decode(_iprot: TProtocol): SiteFlagAddedPb =
    _iprot match {
      case i: LazyTProtocol => lazyDecode(i)
      case i => eagerDecode(i)
    }

  private[this] def eagerDecode(_iprot: TProtocol): SiteFlagAddedPb = {
    var siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = _root_.scala.None
    var _passthroughFields: Builder[(Short, TFieldBlob), immutable$Map[Short, TFieldBlob]] = null
    var _done = false

    _iprot.readStructBegin()
    while (!_done) {
      val _field = _iprot.readFieldBegin()
      if (_field.`type` == TType.STOP) {
        _done = true
      } else {
        _field.id match {
          case 1 =>
            _field.`type` match {
              case TType.I32 | TType.ENUM =>
                siteFlag = _root_.scala.Some(readSiteFlagValue(_iprot))
              case _actualType =>
                val _expectedType = TType.ENUM
                throw new TProtocolException(
                  "Received wrong type for field 'siteFlag' (expected=%s, actual=%s).".format(
                    ttypeToString(_expectedType),
                    ttypeToString(_actualType)
                  )
                )
            }
          case _ =>
            if (_passthroughFields == null)
              _passthroughFields = immutable$Map.newBuilder[Short, TFieldBlob]
            _passthroughFields += (_field.id -> TFieldBlob.read(_field, _iprot))
        }
        _iprot.readFieldEnd()
      }
    }
    _iprot.readStructEnd()

    new Immutable(
      siteFlag,
      if (_passthroughFields == null)
        NoPassthroughFields
      else
        _passthroughFields.result()
    )
  }

  def apply(
    siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = _root_.scala.None
  ): SiteFlagAddedPb =
    new Immutable(
      siteFlag
    )

  def unapply(_item: SiteFlagAddedPb): _root_.scala.Option[_root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb]] = _root_.scala.Some(_item.siteFlag)


  @inline private def readSiteFlagValue(_iprot: TProtocol): com.komanov.serialization.domain.thriftscala.SiteFlagPb = {
    com.komanov.serialization.domain.thriftscala.SiteFlagPb.getOrUnknown(_iprot.readI32())
  }

  @inline private def writeSiteFlagField(siteFlag_item: com.komanov.serialization.domain.thriftscala.SiteFlagPb, _oprot: TProtocol): Unit = {
    _oprot.writeFieldBegin(SiteFlagFieldI32)
    writeSiteFlagValue(siteFlag_item, _oprot)
    _oprot.writeFieldEnd()
  }

  @inline private def writeSiteFlagValue(siteFlag_item: com.komanov.serialization.domain.thriftscala.SiteFlagPb, _oprot: TProtocol): Unit = {
    _oprot.writeI32(siteFlag_item.value)
  }


  object Immutable extends ThriftStructCodec3[SiteFlagAddedPb] {
    override def encode(_item: SiteFlagAddedPb, _oproto: TProtocol): Unit = { _item.write(_oproto) }
    override def decode(_iprot: TProtocol): SiteFlagAddedPb = SiteFlagAddedPb.decode(_iprot)
    override lazy val metaData: ThriftStructMetaData[SiteFlagAddedPb] = SiteFlagAddedPb.metaData
  }

  /**
   * The default read-only implementation of SiteFlagAddedPb.  You typically should not need to
   * directly reference this class; instead, use the SiteFlagAddedPb.apply method to construct
   * new instances.
   */
  class Immutable(
      val siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends SiteFlagAddedPb {
    def this(
      siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = _root_.scala.None
    ) = this(
      siteFlag,
      Map.empty
    )
  }

  /**
   * This is another Immutable, this however keeps strings as lazy values that are lazily decoded from the backing
   * array byte on read.
   */
  private[this] class LazyImmutable(
      _proto: LazyTProtocol,
      _buf: Array[Byte],
      _start_offset: Int,
      _end_offset: Int,
      val siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb],
      override val _passthroughFields: immutable$Map[Short, TFieldBlob])
    extends SiteFlagAddedPb {

    override def write(_oprot: TProtocol): Unit = {
      _oprot match {
        case i: LazyTProtocol => i.writeRaw(_buf, _start_offset, _end_offset - _start_offset)
        case _ => super.write(_oprot)
      }
    }


    /**
     * Override the super hash code to make it a lazy val rather than def.
     *
     * Calculating the hash code can be expensive, caching it where possible
     * can provide significant performance wins. (Key in a hash map for instance)
     * Usually not safe since the normal constructor will accept a mutable map or
     * set as an arg
     * Here however we control how the class is generated from serialized data.
     * With the class private and the contract that we throw away our mutable references
     * having the hash code lazy here is safe.
     */
    override lazy val hashCode = super.hashCode
  }

  /**
   * This Proxy trait allows you to extend the SiteFlagAddedPb trait with additional state or
   * behavior and implement the read-only methods from SiteFlagAddedPb using an underlying
   * instance.
   */
  trait Proxy extends SiteFlagAddedPb {
    protected def _underlying_SiteFlagAddedPb: SiteFlagAddedPb
    override def siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = _underlying_SiteFlagAddedPb.siteFlag
    override def _passthroughFields = _underlying_SiteFlagAddedPb._passthroughFields
  }
}

trait SiteFlagAddedPb
  extends ThriftStruct
  with scala.Product1[Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb]]
  with java.io.Serializable
{
  import SiteFlagAddedPb._

  def siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb]

  def _passthroughFields: immutable$Map[Short, TFieldBlob] = immutable$Map.empty

  def _1 = siteFlag


  /**
   * Gets a field value encoded as a binary blob using TCompactProtocol.  If the specified field
   * is present in the passthrough map, that value is returned.  Otherwise, if the specified field
   * is known and not optional and set to None, then the field is serialized and returned.
   */
  def getFieldBlob(_fieldId: Short): _root_.scala.Option[TFieldBlob] = {
    lazy val _buff = new TMemoryBuffer(32)
    lazy val _oprot = new TCompactProtocol(_buff)
    _passthroughFields.get(_fieldId) match {
      case blob: _root_.scala.Some[TFieldBlob] => blob
      case _root_.scala.None => {
        val _fieldOpt: _root_.scala.Option[TField] =
          _fieldId match {
            case 1 =>
              if (siteFlag.isDefined) {
                writeSiteFlagValue(siteFlag.get, _oprot)
                _root_.scala.Some(SiteFlagAddedPb.SiteFlagField)
              } else {
                _root_.scala.None
              }
            case _ => _root_.scala.None
          }
        _fieldOpt match {
          case _root_.scala.Some(_field) =>
            val _data = Arrays.copyOfRange(_buff.getArray, 0, _buff.length)
            _root_.scala.Some(TFieldBlob(_field, _data))
          case _root_.scala.None =>
            _root_.scala.None
        }
      }
    }
  }

  /**
   * Collects TCompactProtocol-encoded field values according to `getFieldBlob` into a map.
   */
  def getFieldBlobs(ids: TraversableOnce[Short]): immutable$Map[Short, TFieldBlob] =
    (ids flatMap { id => getFieldBlob(id) map { id -> _ } }).toMap

  /**
   * Sets a field using a TCompactProtocol-encoded binary blob.  If the field is a known
   * field, the blob is decoded and the field is set to the decoded value.  If the field
   * is unknown and passthrough fields are enabled, then the blob will be stored in
   * _passthroughFields.
   */
  def setField(_blob: TFieldBlob): SiteFlagAddedPb = {
    var siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = this.siteFlag
    var _passthroughFields = this._passthroughFields
    _blob.id match {
      case 1 =>
        siteFlag = _root_.scala.Some(readSiteFlagValue(_blob.read))
      case _ => _passthroughFields += (_blob.id -> _blob)
    }
    new Immutable(
      siteFlag,
      _passthroughFields
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetField(_fieldId: Short): SiteFlagAddedPb = {
    var siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = this.siteFlag

    _fieldId match {
      case 1 =>
        siteFlag = _root_.scala.None
      case _ =>
    }
    new Immutable(
      siteFlag,
      _passthroughFields - _fieldId
    )
  }

  /**
   * If the specified field is optional, it is set to None.  Otherwise, if the field is
   * known, it is reverted to its default value; if the field is unknown, it is removed
   * from the passthroughFields map, if present.
   */
  def unsetSiteFlag: SiteFlagAddedPb = unsetField(1)


  override def write(_oprot: TProtocol): Unit = {
    SiteFlagAddedPb.validate(this)
    _oprot.writeStructBegin(Struct)
    if (siteFlag.isDefined) writeSiteFlagField(siteFlag.get, _oprot)
    if (_passthroughFields.nonEmpty) {
      _passthroughFields.values.foreach { _.write(_oprot) }
    }
    _oprot.writeFieldStop()
    _oprot.writeStructEnd()
  }

  def copy(
    siteFlag: _root_.scala.Option[com.komanov.serialization.domain.thriftscala.SiteFlagPb] = this.siteFlag,
    _passthroughFields: immutable$Map[Short, TFieldBlob] = this._passthroughFields
  ): SiteFlagAddedPb =
    new Immutable(
      siteFlag,
      _passthroughFields
    )

  override def canEqual(other: Any): Boolean = other.isInstanceOf[SiteFlagAddedPb]

  override def equals(other: Any): Boolean =
    canEqual(other) &&
      _root_.scala.runtime.ScalaRunTime._equals(this, other) &&
      _passthroughFields == other.asInstanceOf[SiteFlagAddedPb]._passthroughFields

  override def hashCode: Int = _root_.scala.runtime.ScalaRunTime._hashCode(this)

  override def toString: String = _root_.scala.runtime.ScalaRunTime._toString(this)


  override def productArity: Int = 1

  override def productElement(n: Int): Any = n match {
    case 0 => this.siteFlag
    case _ => throw new IndexOutOfBoundsException(n.toString)
  }

  override def productPrefix: String = "SiteFlagAddedPb"
}