package(default_visibility = ["//src/com/komanov/serialization:__subpackages__"])

scala_library(
    name = "testdata",
    srcs = glob(["*.scala"]),
    deps = ["//src/com/komanov/serialization/domain"],
)
