// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package com.komanov.serialization.domain.protos.site



sealed trait SiteTypePb extends com.trueaccord.scalapb.GeneratedEnum {
  type EnumType = SiteTypePb
  def isUnknownSiteType: Boolean = false
  def isFlash: Boolean = false
  def isSilverlight: Boolean = false
  def isHtml5: Boolean = false
  def isUnrecognized: Boolean = false
  def companion: com.trueaccord.scalapb.GeneratedEnumCompanion[SiteTypePb] = SiteTypePb
}

object SiteTypePb extends com.trueaccord.scalapb.GeneratedEnumCompanion[SiteTypePb] {
  implicit def enumCompanion: com.trueaccord.scalapb.GeneratedEnumCompanion[SiteTypePb] = this
  @SerialVersionUID(0L)
  case object UnknownSiteType extends SiteTypePb {
    val value = 0
    val index = 0
    val name = "UnknownSiteType"
    override def isUnknownSiteType: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Flash extends SiteTypePb {
    val value = 1
    val index = 1
    val name = "Flash"
    override def isFlash: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Silverlight extends SiteTypePb {
    val value = 2
    val index = 2
    val name = "Silverlight"
    override def isSilverlight: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case object Html5 extends SiteTypePb {
    val value = 3
    val index = 3
    val name = "Html5"
    override def isHtml5: Boolean = true
  }
  
  @SerialVersionUID(0L)
  case class Unrecognized(value: Int) extends SiteTypePb {
    val name = "UNRECOGNIZED"
    val index = -1
    override def isUnrecognized: Boolean = true
  }
  
  lazy val values = Seq(UnknownSiteType, Flash, Silverlight, Html5)
  def fromValue(value: Int): SiteTypePb = value match {
    case 0 => UnknownSiteType
    case 1 => Flash
    case 2 => Silverlight
    case 3 => Html5
    case __other => Unrecognized(__other)
  }
  def descriptor: com.google.protobuf.Descriptors.EnumDescriptor = SiteProto.descriptor.getEnumTypes.get(0)
}