scala_library(
    name = "jmh",
    srcs = glob(["*.scala"]),
    deps = [
        "//src/com/komanov/serialization/converters",
        "//src/com/komanov/serialization/domain",
        "//src/com/komanov/serialization/domain/testdata",
        "//third_party:org_openjdk_jmh_jmh_core",
    ],
)
