scala_benchmark_jmh(
    name = "jmh",
    srcs = glob([
        "*.scala",
        "*.java",
    ]),
    deps = [
        "//src/com/komanov/serialization/converters",
        "//src/com/komanov/serialization/domain",
        "//src/com/komanov/serialization/domain/testdata",
    ],
)
